/* Song of the Day — renders the journal DeetsOTD exports.

   Data source: songs.json, a static file generated by DeetsOTD's web
   exporter (storage._journal_rows -> JSON) and committed alongside the
   site. Cloudflare Pages serves it flat; this script fetches it and
   builds the card grid. No framework, no build step — same spirit as
   controls.js. Every visual value comes from a theme/skin token, so the
   cards inherit all 30 theme x skin combos and the ◑ settings menu. */
(function () {
  "use strict";

  var GRID = document.querySelector("[data-sotd-grid]");
  var META = document.querySelector("[data-sotd-meta]");
  if (!GRID) return;

  /* One <audio> shared by every card: starting a new preview stops the
     one already playing, so only a single 30-sec clip is ever audible. */
  var audio = new Audio();
  var playingBtn = null;
  audio.addEventListener("ended", resetPlaying);
  function resetPlaying() {
    if (playingBtn) {
      playingBtn.classList.remove("is-playing");
      playingBtn.setAttribute("aria-label", "Play preview");
      playingBtn.textContent = "►";
      playingBtn = null;
    }
  }
  function togglePreview(btn, url) {
    if (playingBtn === btn) { audio.pause(); resetPlaying(); return; }
    resetPlaying();
    audio.src = url;
    audio.play().catch(function () { resetPlaying(); });
    playingBtn = btn;
    btn.classList.add("is-playing");
    btn.setAttribute("aria-label", "Pause preview");
    btn.textContent = "❚❚";
  }

  function el(tag, cls, text) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text != null) n.textContent = text;
    return n;
  }

  var MONTHS = ["January", "February", "March", "April", "May", "June",
                "July", "August", "September", "October", "November", "December"];

  // 1 -> "1st", 2 -> "2nd", 3 -> "3rd", 4..20 -> "th", etc.
  function ordinal(n) {
    var t = n % 100;
    if (t >= 11 && t <= 13) return n + "th";
    return n + (["th", "st", "nd", "rd"][n % 10] || "th");
  }

  // "2026-06-29" -> "June 29th, 2026". Parsed from the string parts (not
  // new Date) so a UTC date never shifts a day in the local timezone.
  function prettyDate(iso) {
    var m = /^(\d{4})-(\d{2})-(\d{2})/.exec(iso || "");
    if (!m) return iso || "";
    var mo = +m[2];
    if (mo < 1 || mo > 12) return iso;
    return MONTHS[mo - 1] + " " + ordinal(+m[3]) + ", " + m[1];
  }

  /* Cover art, with a graceful fallback: if the artwork URL is missing or
     fails to load, show a themed monogram tile instead of a broken image. */
  function buildCover(song) {
    var cover = el("div", "song__cover");
    var initial = (song.track_name || "?").trim().charAt(0).toUpperCase() || "?";
    var mono = el("span", "song__mono", initial);
    cover.appendChild(mono);

    if (song.artwork_url) {
      var img = el("img", "song__art");
      img.loading = "lazy";
      img.alt = song.album ? song.track_name + " — " + song.album : song.track_name;
      img.addEventListener("load", function () { cover.classList.add("has-art"); });
      img.addEventListener("error", function () { img.remove(); });
      img.src = song.artwork_url;
      cover.appendChild(img);
    }

    if (song.preview_url) {
      var play = el("button", "song__play", "►");
      play.type = "button";
      play.setAttribute("aria-label", "Play preview");
      play.addEventListener("click", function () { togglePreview(play, song.preview_url); });
      cover.appendChild(play);
    }
    return cover;
  }

  function metaLine(song) {
    // "Album · 2007" — drop empty parts so unresolved posts read cleanly.
    var parts = [];
    if (song.album) parts.push(song.album);
    if (song.release_year) parts.push(song.release_year);
    return parts.join(" · ");
  }

  function buildCard(song) {
    var card = el("article", "song");
    if (song.resolved === "no") card.classList.add("song--unresolved");

    card.appendChild(buildCover(song));

    // One body with labeled parts. The view layouts (full/small/line) reflow
    // these purely in CSS — line flattens body/tags/foot with display:contents —
    // so a card is built once and never re-rendered when the view changes.
    var body = el("div", "song__body");

    // title attrs give the full text on hover (native tooltip), since small/line
    // views clamp track/artist/album to one line with an ellipsis.
    var head = el("div", "song__head");
    var trackName = song.track_name || "(unresolved link)";
    var trackEl = el("h2", "song__track", trackName);
    trackEl.title = trackName;
    head.appendChild(trackEl);
    if (song.artist_name) {
      var artistEl = el("p", "song__artist", song.artist_name);
      artistEl.title = song.artist_name;
      head.appendChild(artistEl);
    }
    body.appendChild(head);

    var sub = metaLine(song);
    if (sub) {
      var albumEl = el("p", "song__album", sub);
      albumEl.title = sub;
      body.appendChild(albumEl);
    }

    var tags = el("div", "song__tags");
    if (song.genre) tags.appendChild(el("span", "song__genre song__chip", song.genre));
    if (song.duration) tags.appendChild(el("span", "song__len song__chip song__chip--soft", song.duration));
    if (tags.childNodes.length) body.appendChild(tags);

    var foot = el("div", "song__foot");
    foot.appendChild(el("span", "song__uploader", "@" + (song.author || "someone")));
    foot.appendChild(el("span", "song__date", prettyDate(song.date)));
    body.appendChild(foot);

    // Outbound link — Apple Music if resolved, else the posted source URL.
    // The Discord jump_url is intentionally NOT rendered: it exposes the
    // private server/channel/message IDs on a public site.
    var links = el("div", "song__links");
    if (song.apple_music_url) {
      var am = el("a", "song__link", "Apple Music");
      am.href = song.apple_music_url; am.target = "_blank"; am.rel = "noopener";
      links.appendChild(am);
    } else if (song.url) {
      var src = el("a", "song__link", "Listen");
      src.href = song.url; src.target = "_blank"; src.rel = "noopener";
      links.appendChild(src);
    }
    if (links.childNodes.length) body.appendChild(links);

    card.appendChild(body);
    return card;
  }

  // ── Persisted control state ───────────────────────────────────
  // One blob so Sort/View/Filter/unlock survive reloads. The search query is
  // ephemeral (not persisted), matching DeetsMusic.
  var STATE_KEY = "deets-sotd-state";
  var state = loadState();
  var query = "";
  function loadState() {
    var s = {
      view: "full", sortKey: "added", sortDir: "desc",
      unlocked: false, filterMode: "and",
      filters: { uploaders: [], genres: [], months: [] }
    };
    try {
      var saved = JSON.parse(localStorage.getItem(STATE_KEY) || "{}");
      if (saved.view) s.view = saved.view;
      if (saved.sortKey) s.sortKey = saved.sortKey;
      if (saved.sortDir) s.sortDir = saved.sortDir;
      s.unlocked = !!saved.unlocked;
      if (saved.filterMode) s.filterMode = saved.filterMode;
      if (saved.filters) {
        s.filters.uploaders = saved.filters.uploaders || [];
        s.filters.genres = saved.filters.genres || [];
        s.filters.months = saved.filters.months || [];
      }
    } catch (e) {}
    return s;
  }
  function saveState() { try { localStorage.setItem(STATE_KEY, JSON.stringify(state)); } catch (e) {} }

  // ── Sort ──────────────────────────────────────────────────────
  // Each spec pulls one comparable value; `dir` is the sensible default
  // direction applied when you switch to that sort. Dates parse to numbers.
  var SORTS = [
    { key: "added",    label: "Date added",   type: "num", dir: "desc", get: function (s) { return s.posted_at ? Date.parse(s.posted_at) : null; } },
    { key: "release",  label: "Release date", type: "num", dir: "desc", get: function (s) { return s.release_date ? Date.parse(s.release_date) : null; } },
    { key: "artist",   label: "Artist",       type: "str", dir: "asc",  get: function (s) { return s.artist_name || null; } },
    { key: "uploader", label: "Uploader",     type: "str", dir: "asc",  get: function (s) { return s.author || null; } },
    { key: "length",   label: "Length",       type: "num", dir: "asc",  get: function (s) { return s.duration_sec; } }
  ];
  function sortByKey(key) {
    for (var i = 0; i < SORTS.length; i++) if (SORTS[i].key === key) return SORTS[i];
    return SORTS[0];
  }
  function cmpStr(a, b) { return String(a).localeCompare(String(b), undefined, { sensitivity: "base" }); }
  function sortSongs(items, spec, dir) {
    var sign = dir === "asc" ? 1 : -1;
    return items.slice().sort(function (a, b) {
      var va = spec.get(a), vb = spec.get(b);
      // Missing values always sink to the bottom, whichever direction; track
      // name is the stable tiebreak so equal keys keep a predictable order.
      if (va == null && vb == null) return cmpStr(a.track_name || "", b.track_name || "");
      if (va == null) return 1;
      if (vb == null) return -1;
      var c = spec.type === "num" ? (va - vb) : cmpStr(va, vb);
      return (sign * c) || cmpStr(a.track_name || "", b.track_name || "");
    });
  }

  var VIEWS = [{ key: "full", label: "Full" }, { key: "small", label: "Small" }, { key: "line", label: "Line" }];

  // ── Pipeline: gate -> filter -> search -> sort -> render ──────
  var ALL = [], TOTAL = 0, UPDATED = "";
  function visible() {
    var f = state.filters;
    var q = query.trim().toLowerCase();
    return ALL.filter(function (s) {
      // Vanity gate: while locked, only Deets' picks are shown.
      if (!state.unlocked && s.author !== "Deets") return false;
      // Facets: OR within a facet (each song has one value), AND or OR across
      // facets per the toggle. A facet with no selection adds no constraint.
      var facets = [];
      if (state.unlocked && f.uploaders.length) facets.push(f.uploaders.indexOf(s.author) >= 0);
      if (f.genres.length) facets.push(f.genres.indexOf(s.genre) >= 0);
      if (f.months.length) facets.push(f.months.indexOf(s.month) >= 0);
      if (facets.length) {
        var ok = state.filterMode === "or" ? facets.some(Boolean) : facets.every(Boolean);
        if (!ok) return false;
      }
      // Search: case-insensitive substring over the visible text fields.
      if (q) {
        var hay = (s.track_name + " " + s.artist_name + " " + s.album + " " +
                   s.genre + " " + s.author).toLowerCase();
        if (hay.indexOf(q) < 0) return false;
      }
      return true;
    });
  }
  function refresh() {
    var list = sortSongs(visible(), sortByKey(state.sortKey), state.sortDir);
    GRID.setAttribute("data-view", state.view);
    GRID.textContent = "";
    if (!list.length) {
      GRID.appendChild(el("p", "sotd__empty",
        TOTAL ? "No songs match — try clearing a filter." : "No songs yet — check back soon."));
    } else {
      list.forEach(function (s) { GRID.appendChild(buildCard(s)); });
    }
    setMeta(list.length);
  }
  function setMeta(shown) {
    if (!META) return;
    var line = (shown === TOTAL)
      ? TOTAL + (TOTAL === 1 ? " song" : " songs")
      : shown + " of " + TOTAL + " songs";
    if (UPDATED) line += " · updated " + UPDATED;
    META.textContent = line;
  }

  // ── Toolbar: pills that each open one popover ─────────────────
  var TOOLBAR = document.querySelector("[data-sotd-toolbar]");
  var openEntry = null;
  function closePop() {
    if (!openEntry) return;
    openEntry.pop.hidden = true;
    openEntry.pill.setAttribute("aria-expanded", "false");
    openEntry = null;
    document.removeEventListener("click", onDocClick, true);
    document.removeEventListener("keydown", onDocKey);
  }
  function onDocClick(e) { if (openEntry && !openEntry.ctrl.contains(e.target)) closePop(); }
  function onDocKey(e) { if (e.key === "Escape") { var p = openEntry; closePop(); if (p) p.pill.focus(); } }
  function togglePop(entry) {
    if (openEntry === entry) { closePop(); return; }
    closePop();
    entry.pop.hidden = false;
    entry.pill.setAttribute("aria-expanded", "true");
    openEntry = entry;
    var focusable = entry.pop.querySelector("[data-autofocus]");
    if (focusable) focusable.focus();
    document.addEventListener("click", onDocClick, true);
    document.addEventListener("keydown", onDocKey);
  }
  function makePill(label, fillPop) {
    var ctrl = el("div", "tb-ctrl");
    var pill = el("button", "tb-pill");
    pill.type = "button";
    pill.setAttribute("aria-haspopup", "true");
    pill.setAttribute("aria-expanded", "false");
    pill.appendChild(el("span", "tb-pill__label", label));
    pill.appendChild(el("span", "tb-pill__caret", "▾"));
    var pop = el("div", "tb-pop");
    pop.hidden = true;
    pop.setAttribute("role", "menu");
    var entry = { ctrl: ctrl, pill: pill, pop: pop };
    pill.addEventListener("click", function () { togglePop(entry); });
    ctrl.appendChild(pill);
    ctrl.appendChild(pop);
    fillPop(pop);
    TOOLBAR.appendChild(ctrl);
    return entry;
  }
  function optButton(label, key, isActive, onPick) {
    var b = el("button", "tb-pop__opt", label);
    b.type = "button";
    b.setAttribute("role", "menuitemradio");
    b.dataset.key = key;
    b.setAttribute("aria-checked", String(isActive));
    if (isActive) b.classList.add("is-active");
    b.addEventListener("click", onPick);
    return b;
  }

  function buildSortPill() {
    var pop;
    function mark() {
      pop.querySelectorAll(".tb-pop__opt").forEach(function (b) {
        var on = b.dataset.key === state.sortKey;
        b.classList.toggle("is-active", on); b.setAttribute("aria-checked", String(on));
      });
      pop.querySelectorAll(".tb-pop__dir").forEach(function (b) {
        b.classList.toggle("is-active", b.dataset.dir === state.sortDir);
      });
    }
    makePill("Sort", function (p) {
      pop = p;
      SORTS.forEach(function (spec) {
        p.appendChild(optButton(spec.label, spec.key, spec.key === state.sortKey, function () {
          if (state.sortKey !== spec.key) { state.sortKey = spec.key; state.sortDir = spec.dir; }
          saveState(); mark(); refresh();
        }));
      });
      var dirs = el("div", "tb-pop__dirs");
      [["asc", "Asc ↑"], ["desc", "Desc ↓"]].forEach(function (d) {
        var b = el("button", "tb-pop__dir", d[1]);
        b.type = "button"; b.dataset.dir = d[0];
        if (d[0] === state.sortDir) b.classList.add("is-active");
        b.addEventListener("click", function () { state.sortDir = d[0]; saveState(); mark(); refresh(); });
        dirs.appendChild(b);
      });
      p.appendChild(dirs);
    });
  }

  function buildViewPill() {
    var pop;
    function mark() {
      pop.querySelectorAll(".tb-pop__opt").forEach(function (b) {
        var on = b.dataset.key === state.view;
        b.classList.toggle("is-active", on); b.setAttribute("aria-checked", String(on));
      });
    }
    makePill("View", function (p) {
      pop = p;
      VIEWS.forEach(function (v) {
        p.appendChild(optButton(v.label, v.key, v.key === state.view, function () {
          state.view = v.key; saveState(); mark(); refresh();
        }));
      });
    });
  }

  // ── Filter (vanity gate + uploader / genre / month facets) ────
  var filterEntry = null, searchEntry = null;
  var UPLOADERS = [], GENRES = [], MONTHS_LIST = [];

  function uniqSorted(vals) {
    return Array.from(new Set(vals)).filter(Boolean)
      .sort(function (a, b) { return String(a).localeCompare(String(b)); });
  }
  function monthLabel(m) {
    var i = parseInt(m.slice(0, 2), 10) - 1;
    return (MONTHS[i] || m.slice(0, 2)) + " " + m.slice(3);
  }
  function activeFacetCount() {
    var f = state.filters, n = 0;
    if (state.unlocked && f.uploaders.length) n++;
    if (f.genres.length) n++;
    if (f.months.length) n++;
    return n;
  }
  function filtersActive() {
    var f = state.filters;
    return state.unlocked || f.uploaders.length || f.genres.length || f.months.length;
  }
  function updateFilterPill() {
    if (filterEntry) filterEntry.pill.classList.toggle("is-active", !!filtersActive());
  }
  function updateSearchPill() {
    if (searchEntry) searchEntry.pill.classList.toggle("is-active", !!query.trim());
  }
  function updateCombineDim(pop) {
    var combine = pop.querySelector(".filter-combine");
    if (!combine) return;
    var dim = activeFacetCount() < 2;
    combine.classList.toggle("is-dim", dim);
    combine.querySelectorAll(".filter-combine__btn").forEach(function (b) { b.disabled = dim; });
  }

  function facetGroup(pop, title, key, options, labelFn, searchable) {
    var group = el("div", "filter-group");
    group.appendChild(el("div", "filter-group__title", title));
    var list = el("div", "filter-group__list");
    options.forEach(function (opt) {
      var label = el("label", "filter-check");
      var input = el("input");
      input.type = "checkbox";
      input.checked = state.filters[key].indexOf(opt) >= 0;
      input.addEventListener("change", function () {
        var arr = state.filters[key], i = arr.indexOf(opt);
        if (input.checked && i < 0) arr.push(opt);
        else if (!input.checked && i >= 0) arr.splice(i, 1);
        saveState(); refresh(); updateFilterPill(); updateCombineDim(pop);
      });
      var name = labelFn ? labelFn(opt) : opt;
      label.appendChild(input);
      label.appendChild(el("span", "filter-check__name", name));
      label._match = String(name).toLowerCase();   // cached for the sift box
      list.appendChild(label);
    });
    group.appendChild(list);
    // A little box under a long list (Genre / Month) to sift its options.
    if (searchable) {
      var find = el("input", "filter-search");
      find.type = "search";
      find.placeholder = "Search " + title.toLowerCase() + "s";
      find.addEventListener("input", function () {
        var q = find.value.trim().toLowerCase();
        list.querySelectorAll(".filter-check").forEach(function (row) {
          row.style.display = (!q || row._match.indexOf(q) >= 0) ? "" : "none";
        });
      });
      group.appendChild(find);
    }
    return group;
  }

  function buildFilterPop(pop) {
    pop.classList.add("tb-pop--filter");
    pop.textContent = "";

    // Gate on top: the vanity "Moshi" unlock — just the box when locked
    // (unlock on Enter); once unlocked, only a "Lock again" link.
    var gate = el("div", "filter-gate");
    if (state.unlocked) {
      var relock = el("button", "filter-gate__link", "Lock again");
      relock.type = "button";
      relock.addEventListener("click", function () {
        state.unlocked = false; state.filters.uploaders = [];
        saveState(); buildFilterPop(pop); refresh(); updateFilterPill();
      });
      gate.appendChild(relock);
    } else {
      var input = el("input", "filter-gate__input");
      input.type = "text"; input.placeholder = "Password";
      input.setAttribute("aria-label", "Password to show everyone’s picks");
      input.setAttribute("data-autofocus", "");
      input.addEventListener("keydown", function (e) {
        if (e.key !== "Enter") return;
        e.preventDefault();
        if (input.value.trim().toLowerCase() === "moshi") {
          state.unlocked = true; saveState(); buildFilterPop(pop); refresh(); updateFilterPill();
        } else {
          gate.classList.remove("shake"); void gate.offsetWidth; gate.classList.add("shake");
          input.select();
        }
      });
      gate.appendChild(input);
    }
    pop.appendChild(gate);

    // Facets. Uploader only appears once unlocked (locked = Deets only anyway).
    if (state.unlocked) pop.appendChild(facetGroup(pop, "Uploader", "uploaders", UPLOADERS, null));
    pop.appendChild(facetGroup(pop, "Genre", "genres", GENRES, null, true));
    pop.appendChild(facetGroup(pop, "Month", "months", MONTHS_LIST, monthLabel, true));

    // Footer: cross-facet combine toggle (dim until 2+ facets active) + clear.
    var foot = el("div", "filter-foot");
    var combine = el("div", "filter-combine");
    [["and", "AND"], ["or", "OR"]].forEach(function (m) {
      var b = el("button", "filter-combine__btn", m[1]); b.type = "button"; b.dataset.mode = m[0];
      if (m[0] === state.filterMode) b.classList.add("is-active");
      b.addEventListener("click", function () {
        state.filterMode = m[0]; saveState();
        combine.querySelectorAll(".filter-combine__btn").forEach(function (x) {
          x.classList.toggle("is-active", x.dataset.mode === state.filterMode);
        });
        refresh();
      });
      combine.appendChild(b);
    });
    foot.appendChild(combine);
    var clear = el("button", "filter-clear", "Clear filters"); clear.type = "button";
    clear.addEventListener("click", function () {
      state.filters = { uploaders: [], genres: [], months: [] };
      saveState(); buildFilterPop(pop); refresh(); updateFilterPill();
    });
    foot.appendChild(clear);
    pop.appendChild(foot);

    updateCombineDim(pop);
  }

  function buildFilterPill() { filterEntry = makePill("Filter", buildFilterPop); updateFilterPill(); }

  // ── Search (live case-insensitive substring) ──────────────────
  function buildSearchPill() {
    searchEntry = makePill("Search", function (pop) {
      pop.classList.add("tb-pop--search");
      var input = el("input", "tb-search__input");
      input.type = "search"; input.placeholder = "Search title, artist, album…";
      input.value = query;
      input.setAttribute("data-autofocus", "");
      input.addEventListener("input", function () { query = input.value; updateSearchPill(); refresh(); });
      pop.appendChild(input);
      var clr = el("button", "tb-search__clear", "Clear"); clr.type = "button";
      clr.addEventListener("click", function () { query = ""; input.value = ""; updateSearchPill(); refresh(); input.focus(); });
      pop.appendChild(clr);
    });
    updateSearchPill();
  }

  fetch("./songs.json", { cache: "no-cache" })
    .then(function (r) { if (!r.ok) throw new Error(r.status); return r.json(); })
    .then(function (data) {
      ALL = (data && data.songs) || [];
      TOTAL = ALL.length;
      UPDATED = data.generated_at ? prettyDate(data.generated_at.slice(0, 10)) : "";
      UPLOADERS = uniqSorted(ALL.map(function (s) { return s.author; }));
      GENRES = uniqSorted(ALL.map(function (s) { return s.genre; }));
      MONTHS_LIST = Array.from(new Set(ALL.map(function (s) { return s.month; })))
        .filter(function (m) { return m && m !== "unknown"; })
        .sort(function (a, b) {   // newest month first (compare YYYYMM)
          return (b.slice(3) + b.slice(0, 2)).localeCompare(a.slice(3) + a.slice(0, 2));
        });
      if (TOOLBAR) { buildSortPill(); buildViewPill(); buildFilterPill(); buildSearchPill(); }
      refresh();
    })
    .catch(function () {
      GRID.textContent = "";
      GRID.appendChild(el("p", "sotd__empty",
        "Couldn't load the journal. Try again in a moment."));
    });
})();
