/* DeetsRadio - Apple Music developer token (generated by scripts/radio-token.ps1).
   Public by design: an origin-locked ES256 JWT that ships to every visitor.
   Re-signed automatically when within 30 days of expiry
   (see scripts/register-nightly-radio-token.ps1). Do not hand-edit.
   exp: 2026-12-10 */
window.RADIO_DEV_TOKEN = "eyJhbGciOiJFUzI1NiIsImtpZCI6IjU2ODU3MjhTV1MifQ.eyJpc3MiOiI1UEZEUzM2NUE4IiwiaWF0IjoxNzgzOTY0MTk0LCJleHAiOjE3OTY5MjQxOTQsIm9yaWdpbiI6WyJodHRwczovL2RlZXRzLnNvbHV0aW9ucyIsImh0dHA6Ly9sb2NhbGhvc3Q6ODc4NyIsImh0dHA6Ly9sb2NhbGhvc3Q6ODc4OCJdfQ.m2hyJybTmziaYDvz8wZjJgYaz8sPuDyxKWHbUXPjbjmzQ2V58I6tsxa_rJJ-S5oHg8cTyp3wm6hqitfkQnCvag";