/* DeetsShips — UI copy (docs/ships.md).

   EVERY user-facing string on the ships page lives in this one flat
   object: gate copy, buttons, the lobby, the planning surface, the guide,
   empty states, and the class display names. ships.js holds no flavor
   copy of its own — the terse mechanical LOG lines are Claude-authored in
   ships.js, rendered from typed event records (they pull display names
   from here).

   Radio convention, verbatim: Claude may ADD a string when wiring new UI,
   but every Claude-authored value must be prefixed "[ph]" — a placeholder
   Aditya rewrites, deleting the prefix as he goes. Claude never edits an
   un-prefixed (handwritten) value, and nothing still carrying "[ph]" may
   ship. Aditya's copy pass has NOT happened yet: every entry below is
   [ph].

   {curly} tokens are filled by ships.js (fmt()). */
window.SHIPS_STRINGS = {
  /* ── bar ─────────────────────────────────────────────────────── */
  tableCodePlaceholder: "[ph]Table Code",
  yourTables:           "[ph]Recents",

  /* ── peek / create gate ──────────────────────────────────────── */
  peekFull:     "[ph]Table full | {spectators} spectating",
  peekPlayers:  "[ph]{seated} players | {spectators} spectating",
  sitButton:    "[ph]Sit down",
  watchButton:  "[ph]Spectate",
  rejoinButton: "[ph]Rejoin or spectate",
  createLine:   "[ph]The '{code}' Table doesn't exist yet. Open it?",
  createButton: "[ph]Open the Table",
  nameLabel:    "[ph]Your name",
  nameNeeded:   "[ph]Enter a name first.",
  peekFailed:   "[ph]Couldn't join the table. Try again soon!",

  /* ── toolbar pills ───────────────────────────────────────────── */
  invitePill:   "[ph]Invite",
  settingsPill: "[ph]View Settings",
  shareToast:   "[ph]Invite link copied!",
  sitPill:      "[ph]Sit down",
  leavePill:    "[ph]Leave",
  closePill:    "[ph]Close Table",
  closeConfirm: "[ph]Confirm?",
  tableClosed:  "[ph]The host closed the table.",

  /* ── lobby ───────────────────────────────────────────────────── */
  lobbyTitle:      "[ph]Table settings",
  sizeLabel:       "[ph]Table size",
  sizeOption:      "[ph]{n}v{n}",
  timerDraftLabel: "[ph]Draft timer",
  timerMoveLabel:  "[ph]Move timer",
  timerActionLabel:"[ph]Action timer",
  timerOff:        "[ph]Off",
  timerSecs:       "[ph]{n}s",
  lockLabel:       "[ph]Commits lock",
  lockOn:          "[ph]On",
  lockOff:         "[ph]Off",
  fleetsLabel:     "[ph]Fleet lists",
  fleetsPublic:    "[ph]Public",
  fleetsSecret:    "[ph]Secret",
  startButton:     "[ph]Start game",
  shufflePill:     "[ph]Shuffle",
  startHint:       "[ph]The draft opens on press.",
  startNeedsTwo:   "[ph]Need at least 1 player per side.",
  teamsUnevenHint: "[ph]Both sides need the same number of players.",
  seatOpen:        "[ph]Open seat",
  seatYou:         "[ph]{name} (you)",
  hostBadge:       "[ph]Host",
  captainBadge:    "[ph]Captain",
  sitHereButton:   "[ph]Sit here",
  teamWest:        "[ph]West",
  teamEast:        "[ph]East",
  standButton:     "[ph]Stand up",
  standConfirm:    "[ph]Confirm?",
  sitDownPill:     "[ph]Take over for:",
  kickSeatAria:    "[ph]Remove {name}",
  rejoinLabel:     "[ph]Re-joining",
  rejoinAnyone:    "[ph]Anyone",
  rejoinRejoin:    "[ph]Rejoin",
  concededToast:   "[ph]{name} conceded.",
  adoptedToast:    "[ph]{name} sat down.",
  addBotButton:     "[ph]Add Bot",
  addBotGo:         "[ph]Confirm?",
  addBotNameAria:   "[ph]Bot name",
  addBotCancelAria: "[ph]Cancel adding a bot",
  renameBotAria:    "[ph]Rename {name}",
  renameGo:         "[ph]Save",
  renameReset:      "[ph]Reset",
  renameYouAria:    "[ph]Edit your name",
  renameNameAria:   "[ph]Your name",
  renameResetAria:  "[ph]Reset to your profile name",
  renameCancelAria: "[ph]Cancel renaming",
  colorYours:      "[ph]Your side's color",
  colorTheirs:     "[ph]{name}'s color",
  colorBecome:     "[ph]Become...",
  colorDotAria:    "[ph]Change color for {name}",
  colorSwatchAria: "[ph]Claim this color",
  colorCustomAria: "[ph]Your custom color",
  colorTakenBy:    "[ph]{name} has this one",
  colorHexLabel:   "[ph]Custom:",
  colorBadHex:     "[ph]Six hex digits, like #1fb0aa",
  colorClashWith:  "[ph]Too close to {name}",
  colorReserved:   "[ph]Red is the ocean's — it marks enemy intel.",

  /* ── class display names ─────────────────────────────────────── */
  clsCarrier:    "[ph]Carrier",
  clsBattleship: "[ph]Battleship",
  clsDestroyer:  "[ph]Destroyer",
  clsSubmarine:  "[ph]Submarine",
  clsCruiser:    "[ph]Cruiser",

  /* ── phase banner (the dice slot) ────────────────────────────── */
  phaseDraft:     "[ph]Draft",
  phaseMove:      "[ph]Move",
  phaseAction:    "[ph]Action",
  phaseRound:     "[ph]Round {n}",
  phaseTurnZero:  "[ph]Turn 0",
  sideReady:      "[ph]{side} is ready",
  sideWaiting:    "[ph]Waiting on {side}",

  /* ── players tile ────────────────────────────────────────────── */
  readyMark:      "[ph]Ready",
  disconnected:   "[ph]Away",

  /* ── the calendar (log tile) ─────────────────────────────────── */
  calendarTitle:  "[ph]Turns",
  calendarLive:   "[ph]Live",
  calendarTurn:   "[ph]{n}",
  calendarNote:   "[ph]Viewing turn {n} — the board is read-only.",
  calendarEmpty:  "[ph]The calendar fills as turns resolve.",

  /* ── planning surface (role tile) ────────────────────────────── */
  yourShips:      "[ph]Your ships",
  noShipsYet:     "[ph]Pick your fleet below.",
  draftSlot:      "[ph]Ship {n}",
  draftPickClass: "[ph]Choose a class",
  draftPlace:     "[ph]Place it on your band",
  draftRotate:    "[ph]Rotate",
  draftMount:     "[ph]Pick the weapon tile",
  draftDone:      "[ph]Placed",
  draftRedo:      "[ph]Redo",
  actMove:        "[ph]Move",
  actHold:        "[ph]Hold",
  actTurnLeft:    "[ph]Turn ↺",
  actTurnRight:   "[ph]Turn ↻",
  actHeading:     "[ph]Heading",
  actFire:        "[ph]Fire",
  actSonar:       "[ph]Sonar",
  actSurface:     "[ph]Surface & fire",
  actSecondMove:  "[ph]Second move",
  actPass:        "[ph]Pass",
  actAimHint:     "[ph]Pick a direction.",
  actZoneHint:    "[ph]Pick the strike zone along the line.",
  actMoveHint:    "[ph]Pick a lit tile to move there.",
  actStagedMove:  "[ph]→ moving",
  actStagedHold:  "[ph]→ holding",
  actStagedFire:  "[ph]→ firing {dir}",
  actStagedSonar: "[ph]→ sweeping",
  actStagedSurface: "[ph]→ surfacing {dir}",
  actStagedPass:  "[ph]→ passing",
  actStagedZone:  "[ph]→ strike at {n}",
  dirN:           "[ph]N",
  dirE:           "[ph]E",
  dirS:           "[ph]S",
  dirW:           "[ph]W",
  readyPill:      "[ph]Ready",
  unreadyPill:    "[ph]Unready",
  commitPill:     "[ph]Commit",
  uncommitPill:   "[ph]Uncommit",
  waitingCaptain: "[ph]Waiting on your captain to commit.",
  committedNote:  "[ph]Committed — waiting on the enemy.",
  disarmedTag:    "[ph]disarmed",
  sunkTag:        "[ph]sunk",
  ownerName:      "[ph]{name}",
  spectatingNote: "[ph]You're spectating — you can see both fleets.",
  heldToast:      "[ph]Invalid move occurred — a ship was held in place.",
  corkedToast:    "[ph]The surfacing failed — something sits above the hull.",
  disarmedToast:  "[ph]Your {cls}'s weapon section was destroyed.",
  sweptToast:     "[ph]Your submarine was swept by enemy sonar.",
  struckToast:    "[ph]Your {cls} took a hit.",
  sunkToastOwn:   "[ph]Your {cls} was sunk.",
  sunkToastEnemy: "[ph]Enemy {cls} sunk!",

  /* ── game over ───────────────────────────────────────────────── */
  gameOver:      "[ph]Game Over",
  winnerLine:    "[ph]{side} wins!",
  drawLine:      "[ph]Mutual destruction — nobody sails home.",
  turnCount:     "[ph]{n} turns",
  statShots:     "[ph]Shots",
  statHits:      "[ph]Hits",
  statSunk:      "[ph]Ships sunk",
  rematchButton: "[ph]Rematch",

  /* ── the guide (board tile, bottom-left) ─────────────────────── */
  guideButton:   "[ph]Guide",
  guideTitle:    "[ph]How DeetsShips plays",
  guideTabPhases:  "[ph]Phases",
  guideTabShips:   "[ph]Ships",
  guideTabActions: "[ph]Actions",
  guideTabIntel:   "[ph]Intel",
  guidePhases: "[ph]Both fleets share one 20×20 ocean under fog. Every round has two phases: MOVE, then ACTION. Each player plans their own ships and presses Ready; the captain commits the side. When both sides commit, everything resolves at once — shots land on post-move positions, and both sides' fire lands together.",
  guidePhasesDraft: "[ph]Turn 0 is the draft: pick your classes (no duplicates within a side), place them secretly in your home band, and choose each ship's hidden weapon tile — shots come from that tile, and losing it disarms the ship.",
  guideShips: "[ph]Five classes. Carrier, battleship and destroyer either turn or move; submarine and cruiser can do both in one phase (the turn costs 1 tile). Ships slide along their axis, forward or backward, and turn 90° about an end tile (or the center on odd hulls). Every hit slows a ship by 2 tiles of movement.",
  guideActions: "[ph]Each ship may fire, take its special action, or pass. Line shots hit the first enemy they meet. The destroyer's missile may bend one row or column, and favors bow and stern tiles. The carrier's plane strikes a 4×3 zone anywhere along its line, hitting everything inside. The submarine lives underwater — only other subs can touch it — and sweeps sonar, but surfacing to attack exposes it for the whole phase. The cruiser's special is a second move.",
  guideIntel: "[ph]Red is enemy information, in three marks: a phantom fill is a detection (sonar, or the 3×3 reveal around a hit), a ✕ is a confirmed hit, and a dotted lane is a shot that found nothing — cleared water. Firing reveals you: within 8 tiles of the target the exact tile, beyond that only a compass bearing. Marks live one turn on the ocean, then move into the calendar — click a past turn to review everything your side ever learned.",
  guideColClass:  "[ph]Class",
  guideColLen:    "[ph]Length",
  guideColMove:   "[ph]Move",
  guideColRange:  "[ph]Range",
  guideRangeBoard:"[ph]Whole board",

  /* ── connection / refusals ───────────────────────────────────── */
  startBotWarn:  "[ph]{n} disconnected seat(s) will be played by bots.",
  connDown:      "[ph]Reconnecting…",
  connUp:        "[ph]Back!",
  replacedToast: "[ph]You opened this table in another tab. Multiple tabs is no bueno, close all but one",
  kickedMeta:    "[ph]The host removed you from the table.",
  tableFull:     "[ph]Table is full.",
  nameTaken:     "[ph]That name is taken at the table.",
  noTable:       "[ph]No such table.",

  /* ── error codes → friendly lines ────────────────────────────── */
  errTurn:  "[ph]That ship isn't yours to order.",
  errPhase: "[ph]Can't do that right now.",
  errPerm:  "[ph]You can't do that.",
  errFull:  "[ph]Table's full.",
  errColor:      "[ph]That's not a hex color.",
  errColorTaken: "[ph]Too close to the other side's color.",
  errFlood:      "[ph]Slow down a moment. Limited to 30 server actions in 10s.",
  errTeams:      "[ph]Both sides need the same number of players.",
  errPlan:       "[ph]That plan doesn't parse.",
  errDupe:       "[ph]Your side already fields one of those.",
  errBand:       "[ph]Ships start inside your home band.",
  errMove:       "[ph]That ship can't reach there.",
  errAim:        "[ph]The gun can't fire that way.",
  errDisarmed:   "[ph]That ship's weapon section is destroyed.",
  errLocked:     "[ph]Commits are locked at this table.",

  /* ── disconnect grace + bot takeover ─────────────────────────── */
  leavingToast:  "[ph]{name} disconnected — a bot takes over in {secs}s",
  returnedToast: "[ph]{name} is back.",
  takeoverToast: "[ph]A bot is now playing {name}'s seat.",
  botSeatTag:    "[ph]{name} (bot)",

  /* ── desktop-only guard ──────────────────────────────────────── */
  desktopOnly: "[ph]DeetsShips needs a wider screen to work rip."
};
