#!/usr/bin/env python3
"""DeetsTanks — level build (docs/tanks.md, "The level format").

Reads every tanks/levels/*.txt (sorted — the filename order IS the
campaign order), validates each, and inlines them all into
tanks/levels.js as strings. A static site has no directory listing, so
the manifest is needed anyway; inlining also means zero fetches at
runtime and validation at build time, not only in the designer.

Validation mirrors engine.js's validateLevel (the engine's parser stays
the authority — this is the build-time gate, failing LOUDLY):
  - grid rectangular, border fully walled
  - only known cells: . # = P 1..9
  - at least one player spawn and one enemy
  - every enemy reachable from the first spawn (flood fill; destructible
    blocks count as passable — a shell opens them)

Usage: python scripts/build-tanks-levels.py
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "tanks" / "levels"
OUT = ROOT / "tanks" / "levels.js"
KNOWN_TYPES = {"1"}          # engine.js ENEMY_TYPES — keep in sync


def parse(text, name):
    rows, in_grid = [], False
    for raw in text.splitlines():
        line = raw.rstrip()
        if in_grid:
            if line:
                rows.append(line)
            continue
        if line.strip() == "grid":
            in_grid = True
    if not rows:
        fail(name, "no grid block")
    w = len(rows[0])
    for i, r in enumerate(rows):
        if len(r) != w:
            fail(name, f"grid not rectangular at row {i}")
    return rows


def fail(name, msg):
    print(f"FAIL {name}: {msg}", file=sys.stderr)
    sys.exit(1)


def validate(rows, name):
    w, h = len(rows[0]), len(rows)
    spawns, enemies = [], []
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            if ch == "P":
                spawns.append((x, y))
            elif ch.isdigit():
                if ch not in KNOWN_TYPES:
                    fail(name, f"unknown enemy type {ch} at {x},{y}")
                enemies.append((x, y))
            elif ch not in ".#=":
                fail(name, f"unknown cell '{ch}' at {x},{y}")
    if not spawns:
        fail(name, "no player spawn")
    if not enemies:
        fail(name, "no enemies")
    for x in range(w):
        if rows[0][x] != "#" or rows[h - 1][x] != "#":
            fail(name, "open border (top/bottom)")
    for y in range(h):
        if rows[y][0] != "#" or rows[y][w - 1] != "#":
            fail(name, "open border (left/right)")
    seen, stack = {spawns[0]}, [spawns[0]]
    while stack:
        cx, cy = stack.pop()
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            nx, ny = cx + dx, cy + dy
            if 0 <= nx < w and 0 <= ny < h and (nx, ny) not in seen and rows[ny][nx] != "#":
                seen.add((nx, ny))
                stack.append((nx, ny))
    for i, e in enumerate(enemies):
        if e not in seen:
            fail(name, f"enemy {i} at {e} unreachable from spawn")


def main():
    files = sorted(SRC.glob("*.txt"))
    if not files:
        fail("levels", f"no level files in {SRC}")
    sources = []
    for f in files:
        text = f.read_text(encoding="utf-8")
        rows = parse(text, f.name)
        validate(rows, f.name)
        sources.append(text.replace("\r\n", "\n").rstrip("\n"))
        print(f"ok  {f.name}  ({len(rows[0])}x{len(rows)})")
    body = ",\n".join(
        "  " + repr_js(src) for src in sources
    )
    OUT.write_text(
        "/* GENERATED by scripts/build-tanks-levels.py — DO NOT HAND-EDIT.\n"
        "   Source of truth: tanks/levels/*.txt (docs/tanks.md). Filename\n"
        "   order is campaign order. Regenerate:\n"
        "     python scripts/build-tanks-levels.py */\n"
        "(function () {\n"
        "  \"use strict\";\n"
        "  var LEVELS = [\n" + body + "\n  ];\n"
        "  if (typeof module !== \"undefined\" && module.exports) module.exports = LEVELS;\n"
        "  if (typeof window !== \"undefined\") window.TANKS_LEVELS = LEVELS;\n"
        "})();\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)} ({len(sources)} levels)")


def repr_js(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


if __name__ == "__main__":
    main()
