"""Build sotd/og.jpg - the link-preview card for deets.solutions/sotd.

Link previews (iMessage, Discord, Slack...) come from static Open Graph
<meta> tags; crawlers never run JS, so the "most recent SOTD" has to be
baked into a real file. This script:

  1. reads sotd/songs.json and picks the most recent song,
  2. fetches its album art (upscaled to 1200x1200 when mzstatic allows),
  3. overlays the front-facing Deets + Happy sprites (vendored from
     DeetsLife under assets/sprites/) bottom-left, nearest-neighbor
     scaled so the pixel art stays crisp,
  4. writes sotd/og.jpg and rewrites the <meta> block in sotd/index.html
     between the "sotd-og" markers (fresh ?v= so caches refetch).

Run by scripts/nightly-sotd.ps1 after a real songs.json change, or by hand:

    python scripts/build-sotd-og.py
"""

import html
import io
import json
import re
import sys
import urllib.request
from datetime import datetime
from pathlib import Path

from PIL import Image

REPO = Path(__file__).resolve().parent.parent
SONGS = REPO / "sotd" / "songs.json"
PAGE = REPO / "sotd" / "index.html"
OUT = REPO / "sotd" / "og.jpg"
SPRITES = REPO / "assets" / "sprites"

CANVAS = 1200          # square card; Discord/iMessage both render it large
SPRITE_FRACTION = 0.24  # Deets' height as a fraction of the canvas

MARK_BEGIN = "<!-- sotd-og:begin"
MARK_END = "<!-- sotd-og:end -->"


def latest_song(songs):
    return max(songs, key=lambda s: s.get("posted_at") or "")


def fetch_artwork(url):
    # mzstatic thumbnails are resizable via the size segment in the path.
    candidates = [url.replace("600x600bb", "1200x1200bb"), url]
    for candidate in candidates:
        try:
            with urllib.request.urlopen(candidate, timeout=30) as resp:
                return Image.open(io.BytesIO(resp.read())).convert("RGB")
        except Exception as e:
            print(f"artwork fetch failed ({candidate}): {e}", file=sys.stderr)
    raise RuntimeError("could not fetch album artwork")


def load_sprite(name):
    img = Image.open(SPRITES / name / "idle_down.png").convert("RGBA")
    return img.crop(img.getbbox())  # trim transparent padding


def compose(art):
    card = art.resize((CANVAS, CANVAS), Image.LANCZOS)

    deets = load_sprite("deets")
    happy = load_sprite("happy")
    scale = max(1, round(CANVAS * SPRITE_FRACTION / deets.height))

    def up(img):
        return img.resize((img.width * scale, img.height * scale), Image.NEAREST)

    deets, happy = up(deets), up(happy)
    margin, gap = 3 * scale, 2 * scale
    baseline = CANVAS - margin
    card.paste(deets, (margin, baseline - deets.height), deets)
    card.paste(happy, (margin + deets.width + gap, baseline - happy.height), happy)
    return card


def average_color(img):
    r, g, b = img.resize((1, 1), Image.LANCZOS).getpixel((0, 0))
    return f"#{r:02x}{g:02x}{b:02x}"


def stamp_page(song, color):
    when = datetime.strptime(song["date"], "%Y-%m-%d")
    version = f"{song['date'].replace('-', '')}-{song['post_id']}"
    track = html.escape(song["track_name"], quote=True)
    artist = html.escape(song["artist_name"], quote=True)
    desc = f"Song of the Day journal. Latest: {track} — {artist} ({when:%b} {when.day})."
    alt = f"Album art for {track} by {artist}, with the Deets and Happy pixel sprites"

    block = "\n".join([
        f"{MARK_BEGIN} (generated by scripts/build-sotd-og.py - do not edit by hand) -->",
        '    <meta property="og:type" content="website" />',
        '    <meta property="og:site_name" content="Deets.Solutions" />',
        '    <meta property="og:title" content="SOTD — Deets" />',
        f'    <meta property="og:description" content="{desc}" />',
        '    <meta property="og:url" content="https://deets.solutions/sotd/" />',
        f'    <meta property="og:image" content="https://deets.solutions/sotd/og.jpg?v={version}" />',
        f'    <meta property="og:image:width" content="{CANVAS}" />',
        f'    <meta property="og:image:height" content="{CANVAS}" />',
        f'    <meta property="og:image:alt" content="{alt}" />',
        '    <meta name="twitter:card" content="summary_large_image" />',
        f'    <meta name="theme-color" content="{color}" />',
        f"    {MARK_END}",
    ])

    page = PAGE.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(MARK_BEGIN) + r".*?" + re.escape(MARK_END), re.DOTALL)
    if not pattern.search(page):
        raise RuntimeError(f"sotd-og markers not found in {PAGE}")
    PAGE.write_text(pattern.sub(lambda _: block, page), encoding="utf-8", newline="\n")


def main():
    songs = json.loads(SONGS.read_text(encoding="utf-8"))["songs"]
    song = latest_song(songs)
    print(f"latest: {song['track_name']} — {song['artist_name']} ({song['date']})")

    art = fetch_artwork(song["artwork_url"])
    card = compose(art)
    card.save(OUT, "JPEG", quality=90, optimize=True)
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB)")

    stamp_page(song, average_color(card))
    print(f"stamped {PAGE}")


if __name__ == "__main__":
    main()
