/* GENERATED by scripts/build-tanks-levels.py — DO NOT HAND-EDIT.
   Source of truth: tanks/levels/*.txt (docs/tanks.md). Filename
   order is campaign order. Regenerate:
     python scripts/build-tanks-levels.py */
(function () {
  "use strict";
  var LEVELS = [
  "﻿name  First Contact\ntier  0\n\ngrid\n####################\n#..................#\n#.................1#\n#..................#\n#..................#\n#..................#\n#..................#\n#..................#\n#..................#\n#P.................#\n#.P................#\n####################",
  "﻿name  Corridors\ntier  1\n\ngrid\n####################\n#P........#.......1#\n#.P.......#........#\n#...####..#..####..#\n#..........=.......#\n#....#....=....#...#\n#....#.........#...#\n#..........=.......#\n#...####..#..####..#\n#.........#........#\n#.........#.......1#\n####################"
  ];
  if (typeof module !== "undefined" && module.exports) module.exports = LEVELS;
  if (typeof window !== "undefined") window.TANKS_LEVELS = LEVELS;
})();
